name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run MathTest
        run: mvn -Dtest=MathTest test   
        
      - name: Run SpeedTest
        run: mvn -Dtest=SpeedTest test
        
      - name: Run TimeoutTest
        run: mvn -Dtest=TimeoutTest test
